/* Generated By:JavaCC: Do not edit this line. CleanCoderParserConstants.java */
package Parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CleanCoderParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 5;
  /** RegularExpression Id. */
  int DOUBLE = 6;
  /** RegularExpression Id. */
  int SHORT = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int LONG = 10;
  /** RegularExpression Id. */
  int CHAR = 11;
  /** RegularExpression Id. */
  int UNSIGNED = 12;
  /** RegularExpression Id. */
  int VOID = 13;
  /** RegularExpression Id. */
  int SMALL_LITERAL = 14;
  /** RegularExpression Id. */
  int LAGRGE_LITERAL = 15;
  /** RegularExpression Id. */
  int DIGITS = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int UNDERBAR = 18;
  /** RegularExpression Id. */
  int EQUAL = 19;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 20;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 21;
  /** RegularExpression Id. */
  int SEMICOLON = 22;
  /** RegularExpression Id. */
  int BACK = 23;
  /** RegularExpression Id. */
  int OTHERS = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\" \"",
    "\"\\t\"",
    "<LINE_COMMENT>",
    "<BLOCK_COMMENT>",
    "\"double\"",
    "\"short\"",
    "\"float\"",
    "\"int\"",
    "\"long\"",
    "\"char\"",
    "\"unsigned\"",
    "\"void\"",
    "<SMALL_LITERAL>",
    "<LAGRGE_LITERAL>",
    "<DIGITS>",
    "\",\"",
    "\"_\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"/\"",
    "<OTHERS>",
  };

}
