/* Generated By:JavaCC: Do not edit this line. CleanCoderCommentParserConstants.java */
package CommentParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CleanCoderCommentParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 3;
  /** RegularExpression Id. */
  int FOR = 4;
  /** RegularExpression Id. */
  int WHILE = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int OTHERS = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "<LINE_COMMENT>",
    "<BLOCK_COMMENT>",
    "\"for\"",
    "\"while\"",
    "\"if\"",
    "<OTHERS>",
  };

}
